### ISSUE TITLE
Error I get when import the codewalker XML's

### ISSUE THREAD

**Issue by YpsilonTM** [pedr0fontoura/gtav-audio-occlusion#1] opened 2021-05-20 19:23 UTC
![image](https://user-images.githubusercontent.com/22861150/119036408-ffaf6700-b9b0-11eb-9b23-3d03c5460d69.png)

![image](https://user-images.githubusercontent.com/22861150/119049950-7ce2d800-b9c1-11eb-8266-d6455ecd9515.png)

I tried the xml's from the nikez example and they work. But the XML i have hase only 1 archtype.

I have tried out some print to see whats wrong, and this is where it seems to go wrong.
In ytyp.ts
![image](https://user-images.githubusercontent.com/22861150/119043563-75b7cc00-b9b9-11eb-8186-a3a4a0d57ba6.png)
the console log
![image](https://user-images.githubusercontent.com/22861150/119043662-908a4080-b9b9-11eb-9192-11f7c2175c87.png)

The length is undefined
Sorry for the screenshots and no code blocks, I will check some more tomorrow or maybe know the problem.

Greetings YpsilonTM, 
Very Nice work btw ! <3

**Comment by AdrineX** [comment] 2021-05-23 13:12
Can confirm, this especially happens when importing Gabz MRPD.

EDIT: I found out that if the .ytyp file dosen't have Item type entry "CBaseArchetypeDef" Tool crashes (this was the issue with Gabz mrpd), if u add it empty like `<Item type="CBaseArchetypeDef"/>` u can generate the files but didn't get the occlusion to work.

**Comment by snakewiz** [comment] 2021-05-23 20:47
I’m aware of the issue. The problem is on this line https://github.com/snakewiz/gtav-audio-occlusion/blob/6cb7d2a747f120468e0b441db6b86f3543847f1d/src/core/files/codewalker/ytyp.ts#L15

Sometimes archetype.Item can be an array or an object

When i get access to my computer, I’m gonna look into it.

**Comment by st860923** [comment] 2021-06-02 13:24
> Can confirm, this especially happens when importing Gabz MRPD.
> 
> EDIT: I found out that if the .ytyp file dosen't have Item type entry "CBaseArchetypeDef" Tool crashes (this was the issue with Gabz mrpd), if u add it empty like `<Item type="CBaseArchetypeDef"/>` u can generate the files but didn't get the occlusion to work.

same as me after replace 
gtav-audio-occlusion/src/core/files/codewalker/ytyp.ts
`const rawArchetype = rawData.CMapTypes.archetypes.Item[archetypesLength - 1]; ` by
`    const rawArchetype = archetypesLength != undefined? rawData.CMapTypes.archetypes.Item[archetypesLength - 1] : rawData.CMapTypes.archetypes.Item
`
compile is good but didn't get the occlusion to work too.

**Comment by snakewiz** [comment] 2021-06-08 21:19
Sorry for the delay, thanks for reporting the issue. Should be fixed as of 4e3d78066311fdeb8e7963a292a6ec417e770072

**Closed as completed by snakewiz** 2021-06-08 21:19 UTC
